### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by Watermalarky** [MartyIce/cointracker#10]
When we tried to log a coin in, But none of us was able to do it there may be a problem, with the code for logging it in.

**Comment by MartyIce** [comment]
Can you please provide reproduction steps, and ideally, screenshots?

I just tried and it seemed OK.  Note that it requires a valid serial number on the coin part, and doesn't "verify" the serial number until you tab out of the serial number (that might be something I need to improve).  But with an invalid serial number, it will give you a validation message:

![screen shot 2016-04-15 at 9 26 30 am](https://cloud.githubusercontent.com/assets/5083039/14564521/885c3d5c-02ec-11e6-862d-f08e1c719390.png)

But once a valid entry has been inputted, it allows you to add city (I just added Moscow to this coin):

![screen shot 2016-04-15 at 9 27 18 am](https://cloud.githubusercontent.com/assets/5083039/14564543/9abf7afe-02ec-11e6-8e7e-21aa0e6839be.png)

**Comment by SpitfireXCIII** [comment]
Whenever we try do an example and log in a coin, even if the city, state, and country is right, it will say "City - Invalid."

**Comment by SpitfireXCIII** [comment]
Here is a screenshot

![screen shot 2016-04-15 at 9 39 55 am](https://cloud.githubusercontent.com/assets/18266905/14564886/1db7fb92-02ee-11e6-933b-672db0b8fd87.png)

**Comment by MartyIce** [comment]
The "State" field is expecting the abbreviation, which is "NV" for Nevada.  We could change this to a dropdown containing all 50 states to make it easier to use, but that would then limit entries to only cities in the 50 US states (nothing outside the country).  Thoughts?

**Comment by SpitfireXCIII** [comment]
Maybe have it to where it says you type in the abbreviation of your state/province or type in the whole name of the state/province? Whichever one you chose would have to make sure you say "State/Province (Abbreviation)." Thanks

**Comment by MartyIce** [comment]
I've updated the code so it will work with EITHER the state abbreviation, or the full state name.
