### ISSUE TITLE
Move the map

### ISSUE THREAD

**Issue by SavannahBleu924** [MartyIce/cointracker#12]
The coin tracker that you made is great, though it is getting kind of long. We would like to move the map that shows where the coins have been. So, instead of the map being under the form you fill out, it will be on the right side of it.

**Comment by MartyIce** [comment]
Can you guys provide a mockup of how you would like the screen laid out?  We currently have 4 sections:

1) Serial Number - on top, this is where user searches for their coin, and it is used to feed the data entry when they add a coin
2) Data entry - on left, this is where city, state, country, created, date, and story are inputtted
3) City list - on right, this displays the cities associated with the currently inputted coin
4) Map - on bottom, this gives a graphical display of the cities.

If you can provide a mockup of how/where you'd like these sections laid out, I can make the changes.

**Comment by Shaalla130** [comment]
We want the serial number, data entry and the city list to stay in the same place. We just want the map to move to the right so its next to the the information boxes. The picture below represents the lay out we want it to look like. 
[screen shot 2016-04-15 at 11 27 06 am](https://cloud.githubusercontent.com/assets/18421832/14568100/0635597e-02fd-11e6-80c5-6db20b9e62df.png)

**Comment by MartyIce** [comment]
map is now on right side, although I believe subsequent issues have asked for the screen to appear differently.  Closing this issue as it's no longer relevant.
