### ISSUE TITLE
Remove Button

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#13]
We would like to remove the button for the map viewing choices,

**Comment by MartyIce** [comment]
Assuming you mean the radio button, I can remove - which map would you like to be permanently displayed?  The one reflected by "Current Coin", or the one for "All Coins"?

**Comment by Shaalla130** [comment]
If were talking about the small map then we want the currents coins to be displayed in that small map.

**Comment by MartyIce** [comment]
map on top now displays all coins' last entry, and map in "info" section in lower part of screen will display path for currently inputted coin.
