### ISSUE TITLE
Color Change

### ISSUE THREAD

**Issue by Watermalarky** [MartyIce/cointracker#15]
Can you make the font color 16549C, and change the color of the page B3C0D3.

**Comment by Watermalarky** [comment]
![image](https://cloud.githubusercontent.com/assets/18421989/14574437/5342b45e-0321-11e6-9df8-5d9550d76e75.png)

**Comment by MartyIce** [comment]
updated colors, please let me know if things look OK.

**Comment by Shaalla130** [comment]
These colors are fine thank you.
