### ISSUE TITLE
Page Size

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#16]
When we put the cointracker into our website the page was to large. We were wondering if you could cut the page down. The pictures below show what the cointracker page looks like on our website.  
[screen shot 2016-04-15 at 3 43 26 pm](https://cloud.githubusercontent.com/assets/18421832/14574404/23df385e-0321-11e6-9031-9798c9bfcecc.png)
![screen shot 2016-04-15 at 3 46 18 pm](https://cloud.githubusercontent.com/assets/18421832/14574445/5c62ed10-0321-11e6-9419-0fb89d5c3346.png)

**Comment by MartyIce** [comment]
I've implemented the following fixes, which hopefully addresses this issue.

https://github.com/MartyIce/cointracker/issues/12
https://github.com/MartyIce/cointracker/issues/13

Please let me know if further work is necessary.
