### ISSUE TITLE
Box size

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#17]
When I went to the example page I saw that the "How'd You Get Your Rock?" box was to big to fit the whole box with all the information in it. Could you make the "How'd You Get Your Rock?" box smaller or could you make the whole box that the information is in bigger? Which ever one works best for you.

**Comment by MartyIce** [comment]
Can you provide a screenshot?  I checked this morning, and the box appears to fit correctly.  It could be appearing strangely in a browser I haven't tested in....

![screen shot 2016-04-18 at 10 29 07 am](https://cloud.githubusercontent.com/assets/5083039/14609644/69b67190-0550-11e6-909f-85036399c747.png)

**Comment by MartyIce** [comment]
Here's current screenshot - please let me know if further adjustments are necessary...

![image](https://cloud.githubusercontent.com/assets/5083039/14612628/cb2e6560-055d-11e6-921c-d05a5ff7c7a7.png)
