### ISSUE TITLE
Big map

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#18]
Since you are putting the current coins on the small map we were wondering if you could make a separate map that shows all the coins. We want to keep that same layout but we want the big map of all the coins to be above everything else. 
![screenshot 2](https://cloud.githubusercontent.com/assets/18421832/14583836/aad451da-03eb-11e6-9729-df3baef0f09f.png)

**Comment by MartyIce** [comment]
updated layout with a big "all coins" map on top of screen.  Please let me know if further layout changes are required.
