### ISSUE TITLE
Connect markers on maps with a line

### ISSUE THREAD

**Issue by yourockrrep** [MartyIce/cointracker#2]
Is there a way to connect the pins in order of entry? That way we see the path the coin has traveled.

**Comment by yourockrrep** [comment]
I am inspired by the map in this picture. I like that it has the connection lines and the numbers of the places it has visited.
![image](https://cloud.githubusercontent.com/assets/18266803/14363250/e61af61a-fcc8-11e5-96d7-ef1679545a4c.png)

**Comment by MartyIce** [comment]
added lines, with numbers represented "visited order".  Note that I'm currently using Google's default "marker icon", which only allows a single digit, and one per city.  So if a city is visited more than once, it will only display the index of the FIRST time it was visited.  We can do this differently if you'd like, explore custom icons, etc.
