### ISSUE TITLE
Map Span

### ISSUE THREAD

**Issue by Watermalarky** [MartyIce/cointracker#22]
Can you increase the size of the world map by making it go across to the other end of the page?

![screen shot 2016-04-19 at 9 15 04 am](https://cloud.githubusercontent.com/assets/18421989/14642244/61683dd8-060f-11e6-9d7a-ac56de62e0de.png)

**Comment by MartyIce** [comment]
Done.  I'm not _completely_ satisfied with the spacing here - wrestling with html/css to get things perfect, but it's much better than it was.
