### ISSUE TITLE
Tittle of Place Box

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#25]
We would like for the box that has the places where the rock has been to have a title. We want the tittle to be "Where the Rocks Have Been".

**Comment by MartyIce** [comment]
I've updated the "global" map on top to have the title "Where the Rocks Have Been".  I couldn't tell whether you were referring to this "top" map, or the "single coin" map in the lower right (the "RockS" made me think you were referring to the top map).  Please let me know if further changes are required.

![screen shot 2016-04-20 at 8 43 24 am](https://cloud.githubusercontent.com/assets/5083039/14676677/26188254-06d4-11e6-8358-89d4b8baf223.png)

**Comment by SpitfireXCIII** [comment]
We would like the "Where the Rocks Have Been" title above the smaller map like you have it on the global map.

**Comment by Shaalla130** [comment]
Sorry for the confusion. We want the tittle "Where the Rock Have Been" to be inside the box with all the places where the rock have been in. The blue box in the screenshot shows where the tittle should be.
![screen shot 2016-04-20 at 9 41 13 am](https://cloud.githubusercontent.com/assets/18421832/14678621/10dbbcbe-06dc-11e6-8b8d-9e9e43a3e0cc.png)

**Comment by MartyIce** [comment]
updated screen accordingly.
