### ISSUE TITLE
Top Tittle

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#26]
Can you change the tittle that says "Got A Rock" to "See Where the World is Currently Rocking!"  We also need for the tittle "Where the Rocks Currently Are" to be deleted if you can. Below there is
screenshots. The screenshot showes what we want it to look like.
![screen shot 2016-04-22 at 9 21 04 am](https://cloud.githubusercontent.com/assets/18421832/14744341/09d12c6a-086c-11e6-8034-67ae342edebb.png)

**Comment by MartyIce** [comment]
Updated:

![screen shot 2016-04-26 at 9 19 32 am](https://cloud.githubusercontent.com/assets/5083039/14821365/1b0e3bea-0b90-11e6-8ce5-c220d260b9ea.png)
