### ISSUE TITLE
"Enter Serial Number" 

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#27]
In the box that says "Enter Serial Number" we would like in the bottom of that title can we have in parenthesis "(Found on Back of Rock"). We also need the box to get slightly bigger but the font to be a little smaller than the tittle "Enter Serial Number". Below is a example of what we want. 
![screen shot 2016-04-22 at 9 47 12 am](https://cloud.githubusercontent.com/assets/18421832/14745077/37d71568-086f-11e6-9a78-0100a56e1b09.png)

**Comment by MartyIce** [comment]
Updated serial number box:

![screen shot 2016-04-26 at 9 18 08 am](https://cloud.githubusercontent.com/assets/5083039/14821300/d4697858-0b8f-11e6-9ac9-1b947646f593.png)
