### ISSUE TITLE
Log Your Rock To Continue The Ripple Effect 

### ISSUE THREAD

**Issue by Watermalarky** [MartyIce/cointracker#28]
Can you add a header in between the big map and the log your rock area that says "Log Your Rock to Continue the Ripple Effect".

![screen shot 2016-04-22 at 9 45 27 am](https://cloud.githubusercontent.com/assets/18421989/14745040/0c7281be-086f-11e6-9ec6-e939c0456a5f.png)

**Comment by MartyIce** [comment]
added:

![screen shot 2016-04-26 at 9 11 35 am](https://cloud.githubusercontent.com/assets/5083039/14821063/ed41f874-0b8e-11e6-9302-bf2fa603fe52.png)
