### ISSUE TITLE
Live coin entry causes spinning in browser

### ISSUE THREAD

**Issue by yourockrrep** [MartyIce/cointracker#30]
We got this email with our first attempt for someone trying to log a coin. Of course it would have to be working fine until we have it go live...

> I am trying to log in with my coin.  When I click on “create coin entry”, it doesn’t appear to be taking.   I’m getting a spinning icon but nothing that indicates acceptance.

**Comment by MartyIce** [comment]
Can you try on your end (and let me know if you need me to delete your tests entry?).  I just entered a rock with no problem...

**Comment by yourockrrep** [comment]
I was not able to get coin 250 log when using Safari 7.0.6, but I was successful in Chrome. I was using my MacBook on my home network. I did not try from Safari on an iPhone interface.

**Comment by MartyIce** [comment]
Fixed issue in Safari - there was a strange authentication issue between Safari, the Rails Server, and the Dennis hosting site.  Should be good now.

**Comment by yourockrrep** [comment]
Tested in Safari this morning again ahead of our rollout field trip in the community. Was not working again in Safari. I was able to log it using Chrome. If there is any chance to resolve this ASAP, that would be great. We will share with others today that they should not use Safari to log at this time.
