### ISSUE TITLE
Coin Entry Erase

### ISSUE THREAD

**Issue by Watermalarky** [MartyIce/cointracker#32]
We were testing the coin tracker and we used the the numbers 008, 100, and 250. Can you remove the entires on those coins?

**Comment by Watermalarky** [comment]
![screen shot 2016-04-29 at 9 14 08 am](https://cloud.githubusercontent.com/assets/18421989/14918677/d0475094-0dea-11e6-97e8-ef8c6a6aec57.png)

**Comment by MartyIce** [comment]
deleted.
