### ISSUE TITLE
Add Box for Stories

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#35]
We were wondering if you could make a box under the map and the information boxes that shows the stories and the rock people have received and the date they received the rock. Since all of the information is going into a data base is it possible for that section to update automatically instead of us going in a changing it?

**Comment by MartyIce** [comment]
Yes, this is something I can add - can you provide a quick mockup of how
you want the overall layout to look (maps, inputs, info box), and I can put
something together?

**Comment by Shaalla130** [comment]
![img_5685](https://cloud.githubusercontent.com/assets/18421832/15250461/790ef5b0-18ea-11e6-92d0-74de0619e00d.JPG)
The information in the purple is a example of what we want.

**Comment by Shaalla130** [comment]
When you add the new box can you tell me what the new dimensions are so we can resize our page to help it fit into the page better.

**Comment by MartyIce** [comment]
I've added the descriptions in a box at the bottom of the page.  The new div is registering in my browser at 244px height.
