### ISSUE TITLE
 Story title 

### ISSUE THREAD

**Issue by Watermalarky** [MartyIce/cointracker#37]
We would like to add a title above the story box, we would like it to be something suitable for many stories like: "See the World's Stories"

![screen shot 2016-05-17 at 9 47 48 am](https://cloud.githubusercontent.com/assets/18421989/15326718/aab099b6-1c14-11e6-8315-e53243e82ab4.png)

**Comment by MartyIce** [comment]
added title - note this pushes the description box down a little, and might require some reformatting on the dennis site...

**Comment by Watermalarky** [comment]
ok
