### ISSUE TITLE
Automatic Stories 

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#38]
We love what you have now, but it would be great if when people first go to the website they didn't see a blank box. Is there any way you could have all the stories be like a realtime feed when we first go to the website, then when you type in your coin number in the "Enter Serial #" it shows that specific coins stories.

**Comment by MartyIce** [comment]
Currently it is only displaying the stories for the currently selected coin - would you like it instead to display ALL stories, regardless of selected coin?

**Comment by MartyIce** [comment]
Just saw you updated the request (was the "when we first go to the website" portion originally there?).  In the future, please just add a new comment with new requirements, etc, and that way I can keep track of what's done, and what needs to be done.  Thanks!

**Comment by MartyIce** [comment]
Implemented "all the stories be like a realtime feed when we first go to the website, then when you type in your coin number in the "Enter Serial #" it shows that specific coins stories.".  Currently they are listed from oldest to newest (oldest at top).
