### ISSUE TITLE
Scroll Box 

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#39]
When we went to our test coin 711 we saw that the stories for it was coming off the box. Could we make the box a scroll box so it doesn't run off of the box?
![screen shot 2016-05-18 at 9 53 47 am](https://cloud.githubusercontent.com/assets/18421832/15363496/877b5376-1cde-11e6-8671-0ed0c2e3e81e.png)

**Comment by MartyIce** [comment]
updated box so that it will scroll.  Also updated logic to not display "and they said" if the person didn't leave a description.
