### ISSUE TITLE
Bug when switching from All coin map back to current coin map

### ISSUE THREAD

**Issue by yourockrrep** [MartyIce/cointracker#6]
When you switch from current map to all coin map it works beautifully. When you try to switch back, the place marks on the map disappear, but are not replaced. In addition the location tracker sidebar does not update from the all coins information.
![screen shot 2016-04-11 at 10 46 10 am](https://cloud.githubusercontent.com/assets/18266803/14433180/db02abee-ffd2-11e5-9df6-3b9962cc761d.png)

**Comment by MartyIce** [comment]
I believe this was due to invalid city data being added to the database.  I've added some validation to prevent this from occurring, and have made the javascript safer for "bad" data.  Pushed latest to heroku, please let me know if you see this behavior in the future.
