### ISSUE TITLE
Coin Tracker Title

### ISSUE THREAD

**Issue by Watermalarky** [MartyIce/cointracker#8]
We would like the title of the coin tracker to change to Got A Rock.

**Comment by MartyIce** [comment]
Changed tab to "Got a Rock".   It current says "Select Coin" at top of page - do we want that to say something different?  eg, "Select Rock"?

**Comment by MartyIce** [comment]
![screen shot 2016-04-13 at 8 34 57 pm](https://cloud.githubusercontent.com/assets/5083039/14514552/5a6273c0-01b7-11e6-9cdd-408687196a7c.png)

**Comment by Shaalla130** [comment]
sorry for the miss communication. We wanted the tittle that said "Select Coin" to be Got a Rock not the tab.

**Comment by MartyIce** [comment]
thanks for clarification - updated.
