### ISSUE TITLE
Tell Your Story

### ISSUE THREAD

**Issue by Shaalla130** [MartyIce/cointracker#9]
We would like to have a box that lets you summit your story when logging in your coin. Instead of leaving a message for the owner like in the example below, we would like it to say summit your story on how you got your rock. If we could have the optional text box in the box where you put the coin information in, that would
![screen shot 2016-04-12 at 9 35 41 am](https://cloud.githubusercontent.com/assets/18421832/14464587/f564cc34-0094-11e6-98fb-2a57308b0657.png)
 be great.

**Comment by MartyIce** [comment]
added a text area input, with "How'd You Get Your Rock?" label on it.  This will save when they add coin entries.  It currently is not displayed anywhere, but is stored in our database.
